start: instruction+

instruction: MOVEMENT NUMBER            -> movement
            |NAME                      -> var
            | "c" COLOR [COLOR]          -> change_color // bgcolor is optional
            | "fill" code_block          -> fill
            | "repeat" NUMBER code_block -> repeat
            |NAME "=" COLOR            -> assign_var

code_block: "{" instruction+ "}"

MOVEMENT: "f"|"b"|"l"|"r"
COLOR: ("a".."z")+
NUMBER: ("0".."9")+
NAME: ("a".."z")+

%import common.WS
%ignore WS